# Generated by Django 3.0.7 on 2020-06-20 19:47

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('mailapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipient',
            name='date_created',
            field=models.DateTimeField(default=datetime.datetime(2020, 6, 20, 19, 47, 21, 688235, tzinfo=utc)),
        ),
        migrations.CreateModel(
            name='RecentMail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(default=django.utils.timezone.now)),
                ('successful', models.IntegerField()),
                ('unsuccessful', models.IntegerField()),
                ('mailing_list', models.EmailField(max_length=254)),
                ('owner', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
