# Generated by Django 3.0.7 on 2020-06-20 19:48

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('mailapp', '0002_auto_20200620_2047'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipient',
            name='date_created',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
