# Generated by Django 3.0.7 on 2020-06-25 02:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mailapp', '0003_auto_20200620_2048'),
    ]

    operations = [
        migrations.AddField(
            model_name='recentmail',
            name='subject',
            field=models.CharField(default='', max_length=200),
            preserve_default=False,
        ),
    ]
