# Generated by Django 3.0.8 on 2020-07-02 02:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mailapp', '0004_recentmail_subject'),
    ]

    operations = [
        migrations.AlterField(
            model_name='action',
            name='action',
            field=models.CharField(choices=[('DL', 'Deleted'), ('CR', 'Created'), ('CD', 'Changed'), ('ED', 'Edited'), ('ST', 'Sent'), ('AD', 'Added'), ('IM', 'Imported')], default='ED', max_length=2),
        ),
    ]
